### ISSUE TITLE
Need a virtual host to deploy crowd sourcing

### ISSUE THREAD

**Issue by cziaarm** [Transkribus/TWI-cs#1]
TWI-cs is a separate project and will need a new apache vhost. We currently have TWI-mc (My Collections) deployed as a vhoat by location at transkribus.eu/read[Test]

I guess we'll need a new location for TWI-cs

Suitable namesfor new location?

transkribus.eu/crowd[Test]?

 (maybe also consider renaming the location for TWI-mc and redirecting from read[Test]??)

**Comment by kahlep** [comment]
Hi Rory,
please check your home directory on read01.uibk.ac.at. There are now directories for the crowd app:
* TransrkibusCrowd
* TranskribusCrowdTest

As soon as you have cloned the github repo there, I can setup the mod_wsgi config for the two contexts:
* crowd
* crowdTest

Open issue:
Separate error logs for the Django apps.
Apache allows separate logging per virtual host. But the current setup (using mod_wsgi, separate deamon process per app. See https://docs.djangoproject.com/en/1.11/howto/deployment/wsgi/modwsgi/) does not work with vhosts so I have to check other solutions.
This may potentially work with SetEnvIf directives as described here: https://stackoverflow.com/questions/1460757/generate-access-logs-for-different-subdirectories-in-apache

What do you think?

**Comment by cziaarm** [comment]
Hi Philip,


I've cloned TWI-cs to TranskribusCrowdTest (I'll leave TranskribusCrowd until we are in a better state)


If you can get the server up I'll take a look (there will be some migrations and potential a few bugs)


I think that the setEnv approach could work. I'm not familiar with it, but it seems straightforward.


Thanks,


Rory

**Comment by kahlep** [comment]
Hi Rory,

when logging in via ssh to the server you should now see a directory called "logs" including separate log-files for each django app. From my perspective it seems to work properly!

This is now configured using the SetEnvIf approach where the request URI has to match a regex for the log to be written to such a file, e.g. "^/crowdTest/.+$". So the trailing slash and some subpath is still mandatory for this to work.

Let me know if there are any adjustments you need on this!

**Comment by kahlep** [comment]
Regexes now end with "/.*$" so only the trailing slash is needed....

**Comment by kahlep** [comment]
Error Log has to be redirected too!

**Comment by cziaarm** [comment]
Hi @kahlep 

Almost there! 

Some of the static content is not being found. This is despite it being present in the same location as files that are served eg:

https://transkribus.eu/crowdTest/static/js/crowd.js

and 

https://transkribus.eu/crowdTest/static/js/read.js

both these are present in /home/webui/TranskribusCrowdTest/collected_static/js/ but only the first is being served.

I *think* this is because the second is a newer addition and requires that the apache server is restarted?

Thanks,

Rory
