### ISSUE TITLE
Access to collection metadata for crowd sourced collections

### ISSUE THREAD

**Issue by cziaarm** [Transkribus/TWI-cs#2]
Need to show collection metadata before login for crowd sourcing projects. To allow potential users to get the measure of a collection before subscribing to the CS project.

- Collection metadata (as outlined, if available, here https://read02.uibk.ac.at/wiki/images/0/0e/READ_webUi.pdf)

Also some document metadata

- document titles
- authors
- thumbnails 
- full images too?
- maybe some of those stats too

**Comment by hackmanschorsch** [comment]
Taken the suggestion from Vili and after some discussions in our team we propose following crowdsourcing metadata:
- Project name
- Description (both exist as collection metadata already)
- Landing page: will be the collection name at start
- Aim of cowdsourcing project (new text box)
- Thumb images: Choose a thumnail for the collection and each document in it via the 'Document Manager' - default is always first image
- News or Milestone table: Here we collect the milestones. Can contain informal dates. But we want to avoid hard dates. As long a collection is a crowd collection as long the collection should be visible and editable. Preventing page edits should be realized with status of pages - 'Done', 'Final' and 'GT' are not editable for crowd users.
@cziaarm Notification of crowd users about milestones could be realized by sending emails with the information what is 'Todo' and what is the due time. This goes into Transkribus as well.

**Comment by hackmanschorsch** [comment]
The crowd project metadata is included in the collection metadata by the next release. So you will get via rest service for each crowd collection:
- name, description, landing page, aim
- 0-n milestones with: id, title, description, due date, date created
- 0-n messages with; id, subject, message, date created and optionally a message can be connected with a milestone (foreign key is the milestone_id)
