### ISSUE TITLE
api: crowdsourcing/list gives 404

### ISSUE THREAD

**Issue by cziaarm** [Transkribus/TWI-cs#4]
https://transkribus.eu/TrpServerTesting/rest/crowdsourcing/list

same for not-Testing
 
https://transkribus.eu/TrpServer/rest/crowdsourcing/list

count seems OK though

**Comment by hackmanschorsch** [comment]
will be fixed after the new server deployment

**Comment by cziaarm** [comment]
Cheers!

**Comment by hackmanschorsch** [comment]
Server is deployed - please test and (hopefully) close this issue.

**Comment by cziaarm** [comment]
Links above are still giving 404

**Comment by hackmanschorsch** [comment]
Server deployed, issue fixed. 
Now you get nrOfDocuments as an additional return value for each collection.
