### ISSUE TITLE
migrating new field to db

### ISSUE THREAD

**Issue by cziaarm** [Transkribus/TWI-cs#5]
please make /home/webui/TranskribusCrowdTest/tmp/db.sqlite3

group writable in order to migrate new fields to db

**Comment by hackmanschorsch** [comment]
webui is owner and group has write access now

**Comment by cziaarm** [comment]
w00t! "working" *first* draft of crowd-courcing interface -> deployed

https://transkribus.eu/crowdTest/

Cheers mate!
